services:
  notifications-svc:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/notification-svc:${IMAGE_TAG:-latest}
    container_name: notifications-svc
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      ITECSMS_API_KEY: ${ITECSMS_API_KEY}
      RESEND_API_KEY: ${RESEND_API_KEY}
      MAIL_FROM: ${MAIL_FROM}
      LOGO_URL: ${LOGO_URL}
    networks:
      - katisha-net

networks:
  katisha-net:
    external: true
